I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labels/capitulo_1/escena_03.rpy", line 16, in script
    python:
  File "game/labels/capitulo_1/escena_03.rpy", line 27, in <module>
    Recoger(Inicializaciones().getEquipable(Inicializaciones.EQUIPABLE_SHINAI)), 0.42, 0.58, 25, 240))
NameError: name 'Inicializaciones' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/labels/capitulo_1/escena_03.rpy", line 16, in script
    python:
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\PROGRAMACIO\renpy-6.18.3-sdk\renpy\python.py", line 1382, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/labels/capitulo_1/escena_03.rpy", line 27, in <module>
    Recoger(Inicializaciones().getEquipable(Inicializaciones.EQUIPABLE_SHINAI)), 0.42, 0.58, 25, 240))
NameError: name 'Inicializaciones' is not defined

Windows-post2008Server-6.2.9200
Ren'Py 6.18.3.761
Reus Quest PreAlpha 0.0.1 0.0
